services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: macqueen_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - macqueen_network

  horizon:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: macqueen_horizon
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan horizon
    volumes:
      - ./:/var/www
    depends_on:
      - app
      - redis
    networks:
      - macqueen_network

  nginx:
    image: nginx:alpine
    container_name: macqueen_nginx
    restart: unless-stopped
    ports:
      - "8847:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - macqueen_network

  db:
    image: mysql:8.0
    container_name: macqueen_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: macqueen
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: macqueen_user
      MYSQL_PASSWORD: secret
    ports:
      - "3347:3306"
    volumes:
      - macqueen_db_data:/var/lib/mysql
    networks:
      - macqueen_network

  redis:
    image: redis:alpine
    container_name: macqueen_redis
    restart: unless-stopped
    ports:
      - "6347:6379"
    networks:
      - macqueen_network

networks:
  macqueen_network:
    driver: bridge

volumes:
  macqueen_db_data:
